services:
  db:
    image: postgres:16
    container_name: manutencao_db
    environment:
      POSTGRES_USER: manutencao
      POSTGRES_PASSWORD: manutencao
      POSTGRES_DB: manutencao
    ports:
      - "5432:5432"          # se quiser expor p/ gerenciador externo
    volumes:
      - db_data:/var/lib/postgresql/data
    networks:
      - manutencao_net

  api:
    build:
      context: ../../        # raiz do monorepo
      dockerfile: infra/intranet/api.Dockerfile
    container_name: manutencao_api
    environment:
      # AJUSTE a URL conforme usuário/senha e nome do serviço (db)
      DATABASE_URL: postgres://manutencao:manutencao@db:5432/manutencao
      JWT_SECRET: super_segredo_trocar
      NODE_ENV: production
      # CORS_ORIGIN vazio pq vamos servir via mesmo host pelo Nginx
      CORS_ORIGIN: ""
      PORT: 3000
    depends_on:
      - db
    networks:
      - manutencao_net

  nginx:
    image: nginx:alpine
    container_name: manutencao_nginx
    volumes:
      # build do front vai cair em apps/web/dist
      - ../../apps/web/dist:/usr/share/nginx/html:ro
      - ./nginx.conf:/etc/nginx/conf.d/default.conf:ro
    ports:
      - "80:80"
    depends_on:
      - api
    networks:
      - manutencao_net

volumes:
  db_data:

networks:
  manutencao_net:
    driver: bridge
